[package]
name = "image-webp-crash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20"
egui_extras = { version = "0.20", features = [ "image" ] }
image = "0.24"
